-- QuadraLevel course learning seed: run after supabase-marketplace-migration.sql.
-- Additive and idempotent: it preserves attempts, submissions, certificates, and user data.

alter table if exists project_submissions
  add column if not exists ai_evaluation jsonb;

alter table if exists project_submissions
  add column if not exists evaluated_at timestamptz;

insert into lessons (course_id, lesson_key, title, position) values ((select id from courses where slug='marketing-launch'), 'ch1', 'مقدمة في التسويق', 1) on conflict (course_id, lesson_key) do update set title=excluded.title, position=excluded.position;
insert into quizzes (course_id, quiz_key, title, passing_score, questions) values ((select id from courses where slug='marketing-launch'), 'quiz-1', 'اختبار مقدمة في التسويق', 70, '[{"q":"التسويق بشكل أساسي هو:","options":["بيع المنتج بأي وسيلة ممكنة","خلق قيمة حقيقية وإيصالها للعميل المناسب","الإعلان فقط","تخفيض الأسعار باستمرار"],"correctIndex":1},{"q":"الفرق الأساسي بين البيع والتسويق:","options":["لا يوجد فرق بينهما","البيع يركز على الصفقة الفورية، والتسويق يبني علاقة وقيمة طويلة المدى","التسويق أرخص من البيع دائمًا","البيع يسبق التسويق دائمًا"],"correctIndex":1},{"q":"من أهم عناصر التسويق الأساسية:","options":["المنتج، السعر، الترويج، التوزيع","الشعار فقط","عدد الموظفين","رأس المال فقط"],"correctIndex":0},{"q":"أحد أكبر تأثيرات ظهور التسويق الرقمي:","options":["اختفاء الحاجة للتسويق التقليدي كليًا","طريقة أدق للوصول للعملاء وقياس النتائج","أصبح بناء العلامة التجارية غير مهم","لم يتغيّر شيء"],"correctIndex":1},{"q":"أي مما يلي مفهوم خاطئ شائع عن التسويق؟","options":["التسويق هو الإعلان فقط","التسويق عملية مستمرة تشمل البحث والتخطيط","التسويق يبدأ بفهم العميل","التسويق مرتبط بخلق قيمة"],"correctIndex":0}]'::jsonb) on conflict (course_id, quiz_key) do update set title=excluded.title, passing_score=excluded.passing_score, questions=excluded.questions;
insert into lessons (course_id, lesson_key, title, position) values ((select id from courses where slug='marketing-launch'), 'ch2', 'رحلة العميل (Customer Journey)', 2) on conflict (course_id, lesson_key) do update set title=excluded.title, position=excluded.position;
insert into quizzes (course_id, quiz_key, title, passing_score, questions) values ((select id from courses where slug='marketing-launch'), 'quiz-2', 'اختبار رحلة العميل (Customer Journey)', 70, '[{"q":"ما هي أول مرحلة في رحلة العميل / قمع المبيعات؟","options":["الشراء","الوعي (Awareness)","الولاء","الاحتفاظ بالعميل"],"correctIndex":1},{"q":"مرحلة \"الاحتفاظ بالعميل\" (Retention) تأتي:","options":["قبل الشراء","بعد الشراء","بدلاً من الوعي","لا علاقة لها بالرحلة"],"correctIndex":1},{"q":"\"المدافعة / التأييد\" (Advocacy) تعني:","options":["العميل يشتري لأول مرة","العميل يوصي بالمنتج للآخرين","العميل يتردد في الشراء","العميل يطلب استرجاع المنتج"],"correctIndex":1},{"q":"مرحلة \"النية\" (Intent) تسبق مباشرة مرحلة:","options":["الوعي","الشراء","الولاء","الاهتمام"],"correctIndex":1},{"q":"فهم رحلة العميل الكاملة يساعد المسوّق على:","options":["تجاهل احتياجات العميل","فهم وتوجيه العميل في كل مرحلة نحو القرار","تقليل جودة المنتج","رفع الأسعار فقط"],"correctIndex":1}]'::jsonb) on conflict (course_id, quiz_key) do update set title=excluded.title, passing_score=excluded.passing_score, questions=excluded.questions;
insert into lessons (course_id, lesson_key, title, position) values ((select id from courses where slug='marketing-launch'), 'ch3', 'فهم العميل (Customer Understanding)', 3) on conflict (course_id, lesson_key) do update set title=excluded.title, position=excluded.position;
insert into quizzes (course_id, quiz_key, title, passing_score, questions) values ((select id from courses where slug='marketing-launch'), 'quiz-3', 'اختبار فهم العميل (Customer Understanding)', 70, '[{"q":"\"شخصية العميل\" (Buyer Persona) هي:","options":["صورة تمثيلية للعميل المثالي مبنية على بيانات حقيقية","اسم المنتج","شعار الشركة","قائمة أسعار"],"correctIndex":0},{"q":"\"نقاط الألم\" (Pain Points) تشير إلى:","options":["مميزات المنتج","المشكلات والتحديات التي يواجهها العميل","أرباح الشركة","عدد الموظفين"],"correctIndex":1},{"q":"العميل في الأساس يشتري:","options":["المنتج نفسه فقط","النتيجة أو الفائدة التي يحصل عليها","اسم الشركة","لون التغليف فقط"],"correctIndex":1},{"q":"فهم \"مخاوف\" العميل يساعد المسوّق على:","options":["تجاهلها","معالجتها وطمأنة العميل قبل الشراء","زيادة السعر دون سبب","قطع التواصل معه"],"correctIndex":1},{"q":"الدوافع النفسية للشراء غالبًا ما تكون:","options":["منطقية بحتة فقط","مزيجًا من العاطفة والمنطق","عشوائية تمامًا","غير قابلة للدراسة"],"correctIndex":1}]'::jsonb) on conflict (course_id, quiz_key) do update set title=excluded.title, passing_score=excluded.passing_score, questions=excluded.questions;
insert into lessons (course_id, lesson_key, title, position) values ((select id from courses where slug='marketing-launch'), 'ch4', 'علم النفس التسويقي (Marketing Psychology)', 4) on conflict (course_id, lesson_key) do update set title=excluded.title, position=excluded.position;
insert into quizzes (course_id, quiz_key, title, passing_score, questions) values ((select id from courses where slug='marketing-launch'), 'quiz-4', 'اختبار علم النفس التسويقي (Marketing Psychology)', 70, '[{"q":"\"التسويق العاطفي\" يعتمد بشكل أساسي على:","options":["الأرقام والإحصائيات فقط","إثارة مشاعر العميل لدفعه لاتخاذ القرار","خفض الأسعار فقط","المواصفات التقنية فقط"],"correctIndex":1},{"q":"\"الانحيازات الإدراكية\" (Cognitive Biases) هي:","options":["أخطاء عشوائية بلا نمط","أنماط تفكير متكررة تؤثر على قرارات الشراء","قوانين تسويقية رسمية","نوع من الإعلانات المدفوعة"],"correctIndex":1},{"q":"الألوان في التسويق:","options":["لا تأثير لها إطلاقًا","تؤثر على المشاعر والانطباعات المرتبطة بالعلامة التجارية","تُستخدم فقط للزينة","لها نفس المعنى في كل الثقافات دائمًا"],"correctIndex":1},{"q":"غالبية قرارات الشراء تُتخذ عبر:","options":["منطق بحت 100%","تأثير عاطفي أولاً يليه تبرير منطقي","عشوائية كاملة","لا علاقة للعاطفة بها إطلاقًا"],"correctIndex":1},{"q":"\"التسويق العصبي\" (Neuromarketing) يدرس:","options":["استجابة الدماغ والجهاز العصبي للمؤثرات التسويقية","الميزانية الإعلانية فقط","عدد المنافسين","توزيع الفروع"],"correctIndex":0}]'::jsonb) on conflict (course_id, quiz_key) do update set title=excluded.title, passing_score=excluded.passing_score, questions=excluded.questions;
insert into lessons (course_id, lesson_key, title, position) values ((select id from courses where slug='marketing-launch'), 'ch5', 'مبادئ التسويق', 5) on conflict (course_id, lesson_key) do update set title=excluded.title, position=excluded.position;
insert into quizzes (course_id, quiz_key, title, passing_score, questions) values ((select id from courses where slug='marketing-launch'), 'quiz-5', 'اختبار مبادئ التسويق', 70, '[{"q":"المزيج التسويقي (Marketing Mix) الأساسي 4Ps يتكوّن من:","options":["Product, Price, Place, Promotion","People, Process, Physical, Product","Plan, Price, Post, Promo","Product, Profit, Place, People"],"correctIndex":0},{"q":"عند الحديث عن الخدمات، يُضاف إلى 4Ps ثلاثة عناصر لتصبح 7Ps، من بينها:","options":["People (الأفراد)","Politics (السياسة)","Population (السكان)","Print (الطباعة)"],"correctIndex":0},{"q":"نموذج STP يبدأ بمرحلة:","options":["Segmentation (تقسيم السوق)","Sales (المبيعات)","Strategy (الاستراتيجية العامة)","Support (الدعم)"],"correctIndex":0},{"q":"في نموذج AIDA، الحرف A الأول يشير إلى:","options":["Advocacy (التأييد)","Attention (الانتباه)","Action (الإجراء)","Awareness فقط بلا انتباه"],"correctIndex":1},{"q":"\"USP\" (الميزة البيعية الفريدة) تجيب على سؤال:","options":["كم سعر المنتج؟","لماذا يشتري العميل منك أنت تحديدًا وليس من المنافسين؟","أين يباع المنتج؟","من هو المدير التنفيذي للشركة؟"],"correctIndex":1}]'::jsonb) on conflict (course_id, quiz_key) do update set title=excluded.title, passing_score=excluded.passing_score, questions=excluded.questions;
insert into lessons (course_id, lesson_key, title, position) values ((select id from courses where slug='marketing-launch'), 'ch6', 'أنواع التسويق (Marketing Types)', 6) on conflict (course_id, lesson_key) do update set title=excluded.title, position=excluded.position;
insert into quizzes (course_id, quiz_key, title, passing_score, questions) values ((select id from courses where slug='marketing-launch'), 'quiz-6', 'اختبار أنواع التسويق (Marketing Types)', 70, '[{"q":"التسويق عبر المؤثرين (Influencer Marketing) يعتمد على:","options":["استخدام أشخاص ذوي تأثير ومتابعين للترويج للمنتج","الإعلانات التلفزيونية فقط","خفض السعر فقط","توزيع منشورات ورقية"],"correctIndex":0},{"q":"التسويق الفيروسي (Viral Marketing) يهدف إلى:","options":["انتشار المحتوى بسرعة كبيرة عبر المشاركة بين الناس","بيع منتج واحد فقط","تقليل عدد المتابعين","إيقاف الحملات الإعلانية"],"correctIndex":0},{"q":"التسويق عبر محركات البحث (SEM/SEO) يركّز على:","options":["الظهور أمام العملاء عند بحثهم عن كلمات متعلقة بمنتجك","توزيع كروت ورقية","الإعلانات في الراديو فقط","لا علاقة له بالإنترنت"],"correctIndex":0},{"q":"إعادة الاستهداف (Retargeting) تعني:","options":["استهداف عملاء جدد تمامًا فقط","إعادة عرض إعلانات لأشخاص تفاعلوا مع المنتج سابقًا ولم يشتروا","حذف بيانات العملاء","إلغاء الحملة الإعلانية"],"correctIndex":1},{"q":"عند اختيار نوع التسويق المناسب لنشاطك التجاري، يجب مراعاة:","options":["طبيعة الجمهور المستهدف والميزانية والأهداف","اختيار كل الأنواع دفعة واحدة دون تخطيط","تقليد المنافس دون تحليل","تجاهل الجمهور المستهدف"],"correctIndex":0}]'::jsonb) on conflict (course_id, quiz_key) do update set title=excluded.title, passing_score=excluded.passing_score, questions=excluded.questions;
insert into lessons (course_id, lesson_key, title, position) values ((select id from courses where slug='marketing-launch'), 'ch7', 'أساسيات العلامة التجارية', 7) on conflict (course_id, lesson_key) do update set title=excluded.title, position=excluded.position;
insert into quizzes (course_id, quiz_key, title, passing_score, questions) values ((select id from courses where slug='marketing-launch'), 'quiz-7', 'اختبار أساسيات العلامة التجارية', 70, '[{"q":"العلامة التجارية (Brand) هي بشكل أساسي:","options":["الشعار فقط","الصورة والانطباع والمشاعر التي تتكون في ذهن العميل","اسم المنتج فقط","لون العبوة فقط"],"correctIndex":1},{"q":"\"الهوية البصرية\" (Visual Identity) تشمل:","options":["الألوان والخطوط والشعار وعناصر التصميم","الأرباح السنوية فقط","عدد الفروع","سياسة الاسترجاع فقط"],"correctIndex":0},{"q":"\"نبرة التواصل\" (Tone of Voice) تعني:","options":["حجم صوت الإعلان التلفزيوني","طريقة وأسلوب حديث العلامة التجارية مع جمهورها","سرعة تحميل الموقع","لون الخط المستخدم فقط"],"correctIndex":1},{"q":"\"التموضع\" (Positioning) هو:","options":["المكانة التي تحتلها العلامة التجارية في ذهن العميل مقارنة بالمنافسين","موقع المتجر الجغرافي فقط","عدد المنتجات المعروضة","سعر المنتج الأساسي"],"correctIndex":0},{"q":"\"وعد العلامة التجارية\" (Brand Promise) هو:","options":["إعلان مؤقت لتخفيضات الموسم","التعهد الذي تقدمه العلامة لعملائها في كل تعامل","اسم المنتج الجديد","عدد الموظفين في الفريق"],"correctIndex":1}]'::jsonb) on conflict (course_id, quiz_key) do update set title=excluded.title, passing_score=excluded.passing_score, questions=excluded.questions;
insert into lessons (course_id, lesson_key, title, position) values ((select id from courses where slug='marketing-launch'), 'ch8', 'أساسيات كتابة المحتوى (Content Writing Basics)', 8) on conflict (course_id, lesson_key) do update set title=excluded.title, position=excluded.position;
insert into quizzes (course_id, quiz_key, title, passing_score, questions) values ((select id from courses where slug='marketing-launch'), 'quiz-8', 'اختبار أساسيات كتابة المحتوى (Content Writing Basics)', 70, '[{"q":"الهدف الأساسي من كتابة المحتوى التسويقي هو:","options":["ملء المساحة فقط دون هدف","تقديم قيمة للجمهور وبناء الثقة وتحقيق هدف تسويقي محدد","استخدام أطول الجمل الممكنة","تجنّب أي عاطفة في الكتابة"],"correctIndex":1},{"q":"نموذج AIDA في كتابة الإعلانات يبدأ بـ:","options":["Attention (جذب الانتباه)","Action (طلب إجراء) مباشرة","Advocacy (التأييد)","Analysis (التحليل)"],"correctIndex":0},{"q":"\"CTA\" في المحتوى التسويقي تعني:","options":["نوعًا من الخطوط","دعوة واضحة لاتخاذ إجراء (Call To Action)","اسم برنامج تصميم","نوعًا من الألوان"],"correctIndex":1},{"q":"\"Storytelling\" (سرد القصص) في المحتوى يساعد على:","options":["تعقيد الرسالة التسويقية بلا داعٍ","خلق ارتباط عاطفي مع الجمهور يجعل الرسالة أكثر تأثيرًا","إخفاء مميزات المنتج","تقليل مصداقية العلامة التجارية"],"correctIndex":1},{"q":"من الأخطاء الشائعة في كتابة المحتوى:","options":["التركيز على احتياج الجمهور","الكتابة بلا هدف واضح أو دعوة لاتخاذ إجراء","استخدام لغة واضحة","مراعاة نبرة العلامة التجارية"],"correctIndex":1}]'::jsonb) on conflict (course_id, quiz_key) do update set title=excluded.title, passing_score=excluded.passing_score, questions=excluded.questions;
insert into lessons (course_id, lesson_key, title, position) values ((select id from courses where slug='marketing-launch'), 'ch9', 'مقدمة في التسويق الرقمي (Digital Marketing Fundamentals)', 9) on conflict (course_id, lesson_key) do update set title=excluded.title, position=excluded.position;
insert into quizzes (course_id, quiz_key, title, passing_score, questions) values ((select id from courses where slug='marketing-launch'), 'quiz-9', 'اختبار مقدمة في التسويق الرقمي (Digital Marketing Fundamentals)', 70, '[{"q":"التسويق الرقمي يشمل بشكل أساسي:","options":["الترويج للمنتجات والخدمات عبر القنوات والمنصات الإلكترونية","الإعلانات المطبوعة فقط","التوزيع عبر المتاجر التقليدية فقط","المكالمات الهاتفية العشوائية فقط"],"correctIndex":0},{"q":"من أهم المنصات الرقمية التي يعمل عليها المسوّق الرقمي:","options":["منصات التواصل الاجتماعي ومحركات البحث والبريد الإلكتروني","المطابع الورقية فقط","اللوحات الإعلانية الثابتة فقط","لا توجد منصات محددة"],"correctIndex":0},{"q":"مسار العميل الرقمي (Digital Customer Path) يساعد المسوّق على:","options":["فهم خطوات العميل الإلكترونية من أول ظهور الإعلان حتى الشراء","تجاهل سلوك العميل على الإنترنت","زيادة السعر تلقائيًا","حذف بيانات العملاء"],"correctIndex":0},{"q":"من مميزات التسويق الرقمي مقارنة بالتقليدي:","options":["إمكانية القياس الدقيق للنتائج واستهداف جمهور محدد","استحالة قياس أي نتيجة","تكلفة أعلى دائمًا بلا استثناء","عدم إمكانية الاستهداف نهائيًا"],"correctIndex":0},{"q":"أنواع الإعلانات الرقمية تشمل غالبًا:","options":["إعلانات البحث والعرض والفيديو والسوشيال ميديا","الإعلانات الإذاعية فقط","المنشورات الورقية فقط","لا يوجد أنواع مختلفة"],"correctIndex":0}]'::jsonb) on conflict (course_id, quiz_key) do update set title=excluded.title, passing_score=excluded.passing_score, questions=excluded.questions;
insert into projects (course_id, project_key, title, instructions, passing_score) values ((select id from courses where slug='marketing-launch'), 'graduation-project', 'مشروع التخرج — Marketing Launch', 'أنشئ خطة إطلاق تسويقية متكاملة لمنتج أو خدمة حقيقية أو افتراضية. وضّح العميل المثالي، القيمة المقترحة، الهوية، القنوات، المحتوى، الإعلانات، الميزانية، مؤشرات القياس، ورحلة العميل.', 70) on conflict (course_id, project_key) do update set title=excluded.title, instructions=excluded.instructions, passing_score=excluded.passing_score;

insert into lessons (course_id, lesson_key, title, position) values ((select id from courses where slug='marketing-growth'), 'ch1', 'أساسيات استراتيجية النمو التسويقي', 1) on conflict (course_id, lesson_key) do update set title=excluded.title, position=excluded.position;
insert into quizzes (course_id, quiz_key, title, passing_score, questions) values ((select id from courses where slug='marketing-growth'), 'quiz-1', 'اختبار أساسيات استراتيجية النمو التسويقي', 70, '[{"q":"ما أول خطوة في بناء استراتيجية تسويقية قابلة للنمو؟","options":["فهم السوق والجمهور المستهدف","شراء أكبر إعلان","تغيير الشعار كل أسبوع"],"correctIndex":0},{"q":"ما فائدة تحديد هدف تسويقي واضح؟","options":["قياس النتائج واختيار الأنشطة المناسبة","منع اختبار الأفكار","زيادة عدد الألوان"],"correctIndex":0},{"q":"ما المقصود بـ Target Audience؟","options":["الجمهور الأكثر احتمالًا للاستفادة والشراء","كل الناس بلا استثناء","فريق التصميم فقط"],"correctIndex":0}]'::jsonb) on conflict (course_id, quiz_key) do update set title=excluded.title, passing_score=excluded.passing_score, questions=excluded.questions;
insert into lessons (course_id, lesson_key, title, position) values ((select id from courses where slug='marketing-growth'), 'ch2', 'الهوية والعلامة التجارية', 2) on conflict (course_id, lesson_key) do update set title=excluded.title, position=excluded.position;
insert into quizzes (course_id, quiz_key, title, passing_score, questions) values ((select id from courses where slug='marketing-growth'), 'quiz-2', 'اختبار الهوية والعلامة التجارية', 70, '[{"q":"ما الهدف الأساسي من الهوية البصرية؟","options":["بناء تعرف وثقة واتساق للعلامة","إخفاء المنتج","تغيير السعر يوميًا"],"correctIndex":0},{"q":"ما الذي يصف Brand Voice؟","options":["طريقة نبرة العلامة في التواصل","نوع الخط فقط","ميزانية الإعلان"],"correctIndex":0},{"q":"لماذا يجب الحفاظ على اتساق العلامة؟","options":["حتى يتعرف الجمهور عليها بسهولة عبر القنوات","حتى تكون كل المنشورات متطابقة حرفيًا","لإلغاء اختبار الرسائل"],"correctIndex":0}]'::jsonb) on conflict (course_id, quiz_key) do update set title=excluded.title, passing_score=excluded.passing_score, questions=excluded.questions;
insert into lessons (course_id, lesson_key, title, position) values ((select id from courses where slug='marketing-growth'), 'ch3', 'صناعة المحتوى', 3) on conflict (course_id, lesson_key) do update set title=excluded.title, position=excluded.position;
insert into quizzes (course_id, quiz_key, title, passing_score, questions) values ((select id from courses where slug='marketing-growth'), 'quiz-3', 'اختبار صناعة المحتوى', 70, '[{"q":"ما وظيفة تقويم المحتوى؟","options":["تنظيم الموضوعات والمواعيد والأهداف","إلغاء التحليل","نشر نفس المنشور يوميًا"],"correctIndex":0},{"q":"ما الترتيب الأفضل للنص التسويقي؟","options":["لفت الانتباه ثم تقديم قيمة ثم دعوة للفعل","السعر فقط ثم الصمت","دعوة للشراء دون سياق"],"correctIndex":0},{"q":"ما المحتوى الجيد؟","options":["محتوى مفيد مرتبط بمشكلة الجمهور وهدف العلامة","محتوى طويل دائمًا","نسخ محتوى المنافسين"],"correctIndex":0}]'::jsonb) on conflict (course_id, quiz_key) do update set title=excluded.title, passing_score=excluded.passing_score, questions=excluded.questions;
insert into lessons (course_id, lesson_key, title, position) values ((select id from courses where slug='marketing-growth'), 'ch4', 'التسويق عبر المنصات الاجتماعية', 4) on conflict (course_id, lesson_key) do update set title=excluded.title, position=excluded.position;
insert into quizzes (course_id, quiz_key, title, passing_score, questions) values ((select id from courses where slug='marketing-growth'), 'quiz-4', 'اختبار التسويق عبر المنصات الاجتماعية', 70, '[{"q":"لماذا تختلف الخطة من منصة إلى أخرى؟","options":["لكل منصة جمهور وسلوك وطريقة استخدام مختلفة","لأن كل المنصات متطابقة","لأن المحتوى لا يحتاج تعديلًا"],"correctIndex":0},{"q":"أي منصة تناسب التسويق المهني وB2B؟","options":["LinkedIn","Pinterest","Snapchat"],"correctIndex":0},{"q":"ما القاعدة المقترحة لتوازن المحتوى؟","options":["80% قيمة و20% بيع","100% بيع","20% قيمة و80% حذف"],"correctIndex":0}]'::jsonb) on conflict (course_id, quiz_key) do update set title=excluded.title, passing_score=excluded.passing_score, questions=excluded.questions;
insert into lessons (course_id, lesson_key, title, position) values ((select id from courses where slug='marketing-growth'), 'ch5', 'الإعلانات المدفوعة وتحسين الحملات', 5) on conflict (course_id, lesson_key) do update set title=excluded.title, position=excluded.position;
insert into quizzes (course_id, quiz_key, title, passing_score, questions) values ((select id from courses where slug='marketing-growth'), 'quiz-5', 'اختبار الإعلانات المدفوعة وتحسين الحملات', 70, '[{"q":"ما الذي يحدد نجاح الإعلان أكثر من حجم الميزانية؟","options":["الاستراتيجية وجودة الإعلان وفهم الجمهور","عدد الألوان","طول اسم الحملة"],"correctIndex":0},{"q":"ما المقصود بـ A/B Testing؟","options":["إنشاء نسختين وتغيير عنصر واحد للمقارنة","إيقاف كل الإعلانات","تغيير كل العناصر مرة واحدة"],"correctIndex":0},{"q":"ماذا يقيس ROAS؟","options":["العائد على الإنفاق الإعلاني","سرعة الموقع","عدد الموظفين"],"correctIndex":0}]'::jsonb) on conflict (course_id, quiz_key) do update set title=excluded.title, passing_score=excluded.passing_score, questions=excluded.questions;
insert into lessons (course_id, lesson_key, title, position) values ((select id from courses where slug='marketing-growth'), 'ch6', 'تحسين الظهور في محركات البحث SEO', 6) on conflict (course_id, lesson_key) do update set title=excluded.title, position=excluded.position;
insert into quizzes (course_id, quiz_key, title, passing_score, questions) values ((select id from courses where slug='marketing-growth'), 'quiz-6', 'اختبار تحسين الظهور في محركات البحث SEO', 70, '[{"q":"ما الهدف العام من SEO؟","options":["تحسين ظهور الموقع وجذب زيارات مناسبة","تغيير كلمة المرور","إرسال رسائل بريدية فقط"],"correctIndex":0},{"q":"ما الفرق بين Short-tail وLong-tail؟","options":["الطويل أكثر تحديدًا عادةً والأقصر أوسع","لا يوجد فرق","القصيرة لا تستخدم في البحث"],"correctIndex":0},{"q":"ما الذي تمثله Backlinks؟","options":["روابط تأتي من مواقع أخرى","صور الموقع","كلمات المرور"],"correctIndex":0}]'::jsonb) on conflict (course_id, quiz_key) do update set title=excluded.title, passing_score=excluded.passing_score, questions=excluded.questions;
insert into lessons (course_id, lesson_key, title, position) values ((select id from courses where slug='marketing-growth'), 'ch7', 'التسويق عبر البريد الإلكتروني', 7) on conflict (course_id, lesson_key) do update set title=excluded.title, position=excluded.position;
insert into quizzes (course_id, quiz_key, title, passing_score, questions) values ((select id from courses where slug='marketing-growth'), 'quiz-7', 'اختبار التسويق عبر البريد الإلكتروني', 70, '[{"q":"ما القاعدة الذهبية لقائمة البريد؟","options":["المتابع يمكن أن يضيع لكن القائمة أصل تملكه","شراء أي قائمة جاهزة","إرسال نفس الرسالة للجميع"],"correctIndex":0},{"q":"ما وظيفة Segmentation؟","options":["تقسيم الجمهور لرسائل أكثر ملاءمة","حذف العملاء","تغيير الشعار"],"correctIndex":0},{"q":"ما المثال الصحيح للأتمتة؟","options":["رسالة ترحيب تُرسل تلقائيًا بعد الاشتراك","كتابة كل رسالة يدويًا فقط","إخفاء زر الإلغاء"],"correctIndex":0}]'::jsonb) on conflict (course_id, quiz_key) do update set title=excluded.title, passing_score=excluded.passing_score, questions=excluded.questions;
insert into lessons (course_id, lesson_key, title, position) values ((select id from courses where slug='marketing-growth'), 'ch8', 'صفحات الهبوط وتحسين التحويل', 8) on conflict (course_id, lesson_key) do update set title=excluded.title, position=excluded.position;
insert into quizzes (course_id, quiz_key, title, passing_score, questions) values ((select id from courses where slug='marketing-growth'), 'quiz-8', 'اختبار صفحات الهبوط وتحسين التحويل', 70, '[{"q":"ما الهدف الأساسي من Landing Page؟","options":["هدف واحد واضح مثل البيع أو التسجيل","عرض كل روابط الموقع","إخفاء العرض"],"correctIndex":0},{"q":"ما المقصود بـ CRO؟","options":["تحسين معدل التحويل","تغيير كلمة المرور","تصميم شعار فقط"],"correctIndex":0},{"q":"ما الذي تساعد عليه Heatmaps؟","options":["فهم أماكن تفاعل الزوار داخل الصفحة","اختيار اسم الشركة","إرسال الفواتير"],"correctIndex":0}]'::jsonb) on conflict (course_id, quiz_key) do update set title=excluded.title, passing_score=excluded.passing_score, questions=excluded.questions;
insert into lessons (course_id, lesson_key, title, position) values ((select id from courses where slug='marketing-growth'), 'ch9', 'بناء مسارات التحويل Funnels', 9) on conflict (course_id, lesson_key) do update set title=excluded.title, position=excluded.position;
insert into quizzes (course_id, quiz_key, title, passing_score, questions) values ((select id from courses where slug='marketing-growth'), 'quiz-9', 'اختبار بناء مسارات التحويل Funnels', 70, '[{"q":"ما المقصود بـ Funnel؟","options":["رحلة تنقل الشخص من التعرف إلى الشراء وما بعده","صفحة تسجيل دخول فقط","نوع من الصور"],"correctIndex":0},{"q":"أي Funnel يركز على جمع بيانات العملاء المحتملين؟","options":["Lead Funnel","Product Funnel","Webinar Funnel"],"correctIndex":0},{"q":"ما الفرق بين Upsell وCross-sell؟","options":["Upsell نسخة أعلى، وCross-sell منتج مكمل","كلاهما نفس الشيء","Upsell جمع البريد فقط"],"correctIndex":0}]'::jsonb) on conflict (course_id, quiz_key) do update set title=excluded.title, passing_score=excluded.passing_score, questions=excluded.questions;
insert into projects (course_id, project_key, title, instructions, passing_score) values ((select id from courses where slug='marketing-growth'), 'graduation-project', 'مشروع التخرج — Marketing Growth', 'أنشئ خطة نمو تسويقي متكاملة لمنتج أو خدمة حقيقية أو افتراضية. وضّح الجمهور، استراتيجية النمو، الهوية، المحتوى، المنصات، الإعلانات، SEO، البريد الإلكتروني، صفحة الهبوط، ومسار التحويل، مع مؤشرات قياس واضحة.', 70) on conflict (course_id, project_key) do update set title=excluded.title, instructions=excluded.instructions, passing_score=excluded.passing_score;

-- Verification: 18 lessons, 18 quizzes, and 2 graduation projects are expected.
select c.slug, count(distinct l.id) as lessons, count(distinct q.id) as quizzes, count(distinct p.id) as projects
from courses c
left join lessons l on l.course_id=c.id
left join quizzes q on q.course_id=c.id
left join projects p on p.course_id=c.id
where c.slug in ('marketing-launch','marketing-growth')
group by c.slug order by c.slug;
